import {useEffect,useRef} from 'react'
import Plotly from 'plotly.js-basic-dist-min'
import type {Asset,Earthquake,PopulationExposure} from '../types'
const config={displayModeBar:false,responsive:true}
const layout={paper_bgcolor:'transparent',plot_bgcolor:'transparent',font:{family:'Inter, sans-serif',color:'#8f9c98',size:10},margin:{l:42,r:12,t:10,b:36},xaxis:{gridcolor:'rgba(255,255,255,.05)',zeroline:false},yaxis:{gridcolor:'rgba(255,255,255,.05)',zeroline:false}}
function Plot({data,layout:chartLayout}:{data:any[];layout:any;[key:string]:any}){const ref=useRef<HTMLDivElement>(null);useEffect(()=>{if(!ref.current)return;Plotly.react(ref.current,data,chartLayout,config);return()=>{if(ref.current)Plotly.purge(ref.current)}},[data,chartLayout]);return <div ref={ref} className='plot'/>}
export function PopulationChart({rows,buffer}: {rows:PopulationExposure[];buffer:number}){const top=[...rows].sort((a,b)=>(b[`population_${buffer}km` as keyof PopulationExposure] as number)-(a[`population_${buffer}km` as keyof PopulationExposure] as number)).slice(0,10);return <Plot className="plot" useResizeHandler data={[{type:'bar',orientation:'h',y:top.map(x=>x.place.split(',')[0]).reverse(),x:top.map(x=>x[`population_${buffer}km` as keyof PopulationExposure] as number).reverse(),marker:{color:'#d7db72'},hovertemplate:'%{y}<br>%{x:,.0f} people<extra></extra>'}]} layout={{...layout,height:210,margin:{...layout.margin,l:95},xaxis:{...layout.xaxis,tickformat:'~s'}}} config={config}/>}
export function MagnitudeChart({events}: {events:Earthquake[]}){const bands=['4.5–5.4','5.5–6.4','6.5+'];const counts=bands.map((_,i)=>events.filter(e=>i===0?e.magnitude<5.5:i===1?e.magnitude<6.5:e.magnitude>=6.5).length);return <Plot className="plot" useResizeHandler data={[{type:'bar',x:bands,y:counts,marker:{color:['#d8cf68','#e3a84d','#ef7351']},hovertemplate:'M%{x}<br>%{y} events<extra></extra>'}]} layout={{...layout,height:210,yaxis:{...layout.yaxis,dtick:1}}} config={config}/>}
export function AssetsChart({assets,buffer}: {assets:Asset[];buffer:number}){const filtered=assets.filter(a=>a.distance_km<=buffer),cats=[...new Set(filtered.map(a=>a.category))],counts=cats.map(c=>filtered.filter(a=>a.category===c).length);return <Plot className="plot" useResizeHandler data={[{type:'pie',labels:cats,values:counts,hole:.62,sort:false,textinfo:'none',marker:{colors:['#78d8c0','#58a6a0','#b6ce71','#e0ba5a','#e38a57','#8a91af','#68736f']},hovertemplate:'%{label}: %{value}<extra></extra>'}]} layout={{...layout,height:210,showlegend:true,legend:{font:{size:9},x:1,y:.9},margin:{l:5,r:105,t:8,b:8},annotations:[{text:`${filtered.length}<br><span style="font-size:9px">ASSETS</span>`,showarrow:false,font:{color:'#eff5ed',size:18}}]}} config={config}/>}



