import {useEffect,useMemo,useState} from 'react'
import {loadDashboard,loadHotspotExposure,loadMl} from './api'
import type {Asset,Cluster,Earthquake,FeatureImportance,HotspotPrediction,ModelMetadata,PopulationExposure,Summary} from './types'
import MapView from './components/MapView'
import {AssetsChart,MagnitudeChart,PopulationChart} from './components/Charts'
import {BuildingIcon,LayersIcon,PinIcon,PulseIcon} from './components/Icons'

const fmt=(n:number)=>Intl.NumberFormat('en',{notation:'compact',maximumFractionDigits:1}).format(n)
const isHotspot=(x:Earthquake|Cluster|HotspotPrediction):x is HotspotPrediction=>'likelihood_score' in x
const isEq=(x:Earthquake|Cluster|HotspotPrediction):x is Earthquake=>'magnitude' in x
function HotspotDetails({item}:{item:HotspotPrediction}){return <>
 <div className="cluster-title"><span className={`status likelihood-${item.category.toLowerCase()}`}>{item.category} likelihood</span><h2>{Math.round(item.likelihood_score*100)}% likelihood score</h2><p>{item.region} • {item.center_latitude.toFixed(1)}°, {item.center_longitude.toFixed(1)}°</p></div>
 <div className="detail-grid three"><div><small>30D EVENTS</small><strong>{item.recent_event_count}</strong></div><div><small>MAX MAG</small><strong>M{item.max_recent_magnitude}</strong></div><div><small>GRID</small><strong>2° × 2°</strong></div></div>
 <div className="brief-section"><h3>Exposure context <em>200 km • approx.</em></h3><div className="metric-row"><span>Nearby population</span><b>{fmt(item.nearby_exposed_population)}</b></div>{item.population_matched_places?.length?<p className="context-note">{item.population_matched_places.slice(0,3).join(' • ')}</p>:null}<div className="metric-row"><span>Critical assets within 200 km</span><b>{item.infrastructure_exposure_status==='loading'?'Loading…':item.infrastructure_exposure_status==='unavailable'?'Unavailable':item.infrastructure_exposure_status==='not_loaded'||!item.infrastructure_exposure_status?'Select to load':item.nearby_critical_infrastructure??'—'}</b></div>{item.infrastructure_by_category?Object.entries(item.infrastructure_by_category).slice(0,4).map(([name,count])=><div className="asset-row" key={name}><span>{name}</span><b>{count}</b></div>):null}</div>
 <div className="brief-section"><h3>Top contributing features</h3>{item.top_contributing_features.slice(0,5).map(f=><div className="feature-row" key={f.feature}><span>{f.name}</span><b>{f.value}</b></div>)}</div>
 <p className="explain">Likelihood score, not prediction certainty. This cell summarizes historical USGS patterns and does not indicate an exact future epicenter.</p>
 </>}
const fallbackSummary:Summary={total_earthquakes:0,active_clusters:0,estimated_exposed_population:0,exposed_critical_assets:0,highest_risk_recent_event:null,updated_at:new Date().toISOString(),source_status:'Loading live open data…',sources:[],disclaimer:''}
export default function App(){
 const [allEq,setAllEq]=useState<Earthquake[]>([]),[clusters,setClusters]=useState<Cluster[]>([]),[population,setPopulation]=useState<PopulationExposure[]>([]),[assets,setAssets]=useState<Asset[]>([]),[summary,setSummary]=useState(fallbackSummary),[loading,setLoading]=useState(true),[error,setError]=useState('')
 const [predictions,setPredictions]=useState<HotspotPrediction[]>([]),[importance,setImportance]=useState<FeatureImportance[]>([]),[mlMetadata,setMlMetadata]=useState<ModelMetadata>({status:'not_trained',title:'Exploratory next-hotspot likelihood based on historical USGS patterns',disclaimer:'This is not an earthquake prediction or public warning system.'})
 const [days,setDays]=useState(30),[minMag,setMinMag]=useState(4.5),[depth,setDepth]=useState<[number,number]>([0,700]),[region,setRegion]=useState('All regions'),[buffer,setBuffer]=useState(200),[selected,setSelected]=useState<Earthquake|Cluster|HotspotPrediction|null>(null),[tab,setTab]=useState<'population'|'infrastructure'>('population'),[layers,setLayers]=useState({clusters:true,population:true,assets:true,hotspots:true})
 const [theme,setTheme]=useState<'dark'|'light'>(()=>(localStorage.getItem('eei-theme') as 'dark'|'light')||'dark')
 useEffect(()=>{localStorage.setItem('eei-theme',theme)},[theme])
 useEffect(()=>{let mounted=true;const poll=()=>loadMl().then(d=>{if(mounted){setPredictions(d.predictions);setImportance(d.importance);setMlMetadata(d.metadata)}}).catch(()=>{});poll();const timer=setInterval(poll,8000);return()=>{mounted=false;clearInterval(timer)}},[])
 useEffect(()=>{setLoading(true);loadDashboard(days).then(d=>{setAllEq(d.earthquakes);setClusters(d.clusters);setPopulation(d.population);setAssets(d.assets);setSummary(d.summary);setSelected([...d.earthquakes].sort((a,b)=>b.magnitude-a.magnitude)[0]||null)}).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[days])
 const regions=useMemo(()=>['All regions',...new Set(allEq.map(e=>e.region).sort())],[allEq])
 const eq=useMemo(()=>{const cut=Date.now()-days*864e5;return allEq.filter(e=>new Date(e.time).getTime()>=cut&&e.magnitude>=minMag&&e.depth_km>=depth[0]&&e.depth_km<=depth[1]&&(region==='All regions'||e.region===region))},[allEq,days,minMag,depth,region])
 const ids=new Set(eq.map(e=>e.id)),pops=population.filter(p=>ids.has(p.earthquake_id)),shownAssets=assets.filter(a=>ids.has(a.earthquake_id)&&a.distance_km<=buffer),shownClusters=clusters.filter(c=>c.event_ids.some(id=>ids.has(id)))
 const exposed=pops.reduce((s,p)=>s+(p[`population_${buffer}km` as keyof PopulationExposure] as number||0),0),highest=[...eq].sort((a,b)=>b.magnitude-a.magnitude)[0]
 const statusColor=(s:string)=>s.startsWith('Emerging')?'amber':s.startsWith('Persistent')?'teal':'slate'
 const selectItem=(item:Earthquake|Cluster|HotspotPrediction)=>{setSelected(item);if(isHotspot(item)&&item.infrastructure_exposure_status!=='loaded'){const loadingItem={...item,infrastructure_exposure_status:'loading' as const};setSelected(loadingItem);loadHotspotExposure(item.id).then(context=>{setPredictions(current=>current.map(cell=>cell.id===item.id?{...cell,...context}:cell));setSelected(current=>current&&isHotspot(current)&&current.id===item.id?{...current,...context}:current)}).catch(()=>setSelected(current=>current&&isHotspot(current)&&current.id===item.id?{...current,infrastructure_exposure_status:'unavailable'}:current))}}
 return <main data-theme={theme}>
  <header><div className="brand-mark"><PulseIcon/></div><div><h1>Earthquake Exposure Intelligence</h1><p>Where seismic activity overlaps with people and critical infrastructure</p></div><div className="header-actions"><button className="theme-toggle" onClick={()=>setTheme(theme==='dark'?'light':'dark')} aria-label={`Switch to ${theme==='dark'?'light':'dark'} theme`}><span>{theme==='dark'?'☀':'☾'}</span>{theme==='dark'?'Light':'Dark'}</button><div className="header-meta"><span className="live-dot"/> OPEN DATA • LIVE CATALOG <small>{summary.source_status}</small></div></div></header>
  <div className="workspace">
   <aside className="filters panel"><div className="panel-title"><span>Analysis controls</span><small>{eq.length} events matched</small></div>
    <label>Date range<div className="segment">{[30,90,365].map(v=><button className={days===v?'active':''} onClick={()=>setDays(v)} key={v}>{v}D</button>)}</div></label>
    <label>Minimum magnitude <strong>M{minMag.toFixed(1)}</strong><input type="range" min="4.5" max="7.5" step="0.1" value={minMag} onChange={e=>setMinMag(+e.target.value)}/><div className="range-label"><span>4.5</span><span>7.5</span></div></label>
    <label>Depth range <strong>{depth[0]}–{depth[1]} km</strong><input type="range" min="25" max="700" step="25" value={depth[1]} onChange={e=>setDepth([0,+e.target.value])}/><div className="range-label"><span>Surface</span><span>700 km</span></div></label>
    <label>Region<select value={region} onChange={e=>setRegion(e.target.value)}>{regions.map(r=><option key={r}>{r}</option>)}</select></label>
    <label>Exposure buffer<div className="segment buffer">{[50,100,200].map(v=><button className={buffer===v?'active':''} onClick={()=>setBuffer(v)} key={v}>{v}<small>km</small></button>)}</div></label>
    <div className="layer-control"><div className="subhead"><LayersIcon/> Map layers</div>{([['clusters','Cluster hulls'],['population','Population buffers'],['assets','Critical assets'],['hotspots','Hotspot likelihood']] as const).map(([k,v])=><button className="layer-row" key={k} onClick={()=>setLayers({...layers,[k]:!layers[k]})}><span className={`legend ${k}`}/>{v}<i className={layers[k]?'on':''}/></button>)}</div>
    <p className="nonprediction">Historical pattern analysis only.<br/><strong>Not an earthquake prediction system.</strong></p>
   </aside>
   <section className="map-shell panel"><MapView earthquakes={eq} clusters={shownClusters} population={pops} assets={shownAssets} predictions={predictions} buffer={buffer} selected={selected} onSelect={selectItem} layers={layers} region={region} theme={theme}/><div className="map-label"><span>{region==='All regions'?'GLOBAL SEISMIC VIEW':region.toUpperCase()}</span><small>USGS M{minMag.toFixed(1)}+ • LAST {days} DAYS</small></div><div className="map-legend"><span><i className="dot amber"/>Earthquake</span><span><i className="line teal"/>Persistent</span><span><i className="line amber"/>Emerging</span></div></section>
   <aside className="details panel"><div className="panel-title"><span>Intelligence brief</span><small>{selected?isHotspot(selected)?'LIKELIHOOD CELL':isEq(selected)?'EVENT':'CLUSTER':'SELECT MAP ITEM'}</small></div>{selected?isHotspot(selected)?<HotspotDetails item={selected}/>:isEq(selected)?<>
    <div className="event-head"><div><small>MAGNITUDE</small><b>{selected.magnitude.toFixed(1)}</b></div><div><h2>{selected.place}</h2><p>{new Date(selected.time).toLocaleString([], {dateStyle:'medium',timeStyle:'short'})}</p></div></div>
    <div className="detail-grid"><div><small>DEPTH</small><strong>{selected.depth_km} km</strong></div><div><small>REGION</small><strong>{selected.region}</strong></div></div>
    <div className="brief-section"><h3>Population exposure <em>approx.</em></h3>{[50,100,200].map(v=>{const p=population.find(x=>x.earthquake_id===selected.id);return <div className={buffer===v?'metric-row chosen':'metric-row'} key={v}><span>Within {v} km</span><b>{fmt((p?.[`population_${v}km` as keyof PopulationExposure] as number)||0)}</b></div>})}</div>
    <div className="brief-section"><h3>Critical infrastructure</h3><div className="big-metric">{assets.filter(a=>a.earthquake_id===selected.id&&a.distance_km<=buffer).length}<span>assets within {buffer} km</span></div>{[...new Set(assets.filter(a=>a.earthquake_id===selected.id).map(a=>a.category))].slice(0,4).map(c=><div className="asset-row" key={c}><span>{c}</span><b>{assets.filter(a=>a.earthquake_id===selected.id&&a.category===c&&a.distance_km<=buffer).length}</b></div>)}</div>
   </>:<>
    <div className="cluster-title"><span className={`status ${statusColor(selected.status)}`}>{selected.status}</span><h2>Cluster {String(selected.id).padStart(2,'0')}</h2><p>{selected.region}</p></div>
    <div className="detail-grid three"><div><small>EVENTS</small><strong>{selected.event_count}</strong></div><div><small>MAX MAG</small><strong>M{selected.max_magnitude}</strong></div><div><small>AVG DEPTH</small><strong>{selected.average_depth_km} km</strong></div></div>
    <div className="activity-compare"><h3>Activity signal</h3><div><span>Recent 7 days <b>{selected.recent_count}</b></span><i><u style={{width:`${Math.min(100,selected.recent_count/Math.max(1,selected.event_count)*100)}%`}}/></i></div><div><span>Baseline <b>{selected.baseline_count}</b></span><i><u style={{width:`${Math.min(100,selected.baseline_count/Math.max(1,selected.event_count)*100)}%`}}/></i></div></div>
    <p className="explain">Status compares the most recent 7 days with the preceding baseline period. It describes observed historical activity, not future likelihood.</p>
   </>:<div className="empty-state"><PinIcon/><p>Select an earthquake, cluster, or likelihood cell on the map to inspect its context.</p></div>}</aside>
  </div>
  <section className="kpis">{[[<PulseIcon/>,eq.length,'Earthquakes analyzed',`M${minMag.toFixed(1)}+ in ${days} days`],[<LayersIcon/>,shownClusters.filter(c=>c.status!=='Dying hotspot').length,'Active clusters','Emerging + persistent'],[<PinIcon/>,fmt(exposed),'Estimated exposed population',`Within ${buffer} km • approximate`],[<BuildingIcon/>,shownAssets.length,'Exposed critical assets',`Within ${buffer} km`],[<PulseIcon/>,highest?`M${highest.magnitude.toFixed(1)}`:'—','Highest-magnitude event',highest?.region||'No matching event']].map((x,i)=><article key={i}><div className="kpi-icon">{x[0]}</div><div><strong>{x[1]}</strong><span>{x[2]}</span><small>{x[3]}</small></div></article>)}</section>
  <section className="ml-section panel"><div className="ml-heading"><div><small>RANDOM FOREST • EXPLORATORY CLASSIFICATION</small><h2>Exploratory Hotspot Likelihood</h2><p>Exploratory next-hotspot likelihood based on historical USGS patterns</p></div><div className={`ml-status ${mlMetadata.status}`}>{mlMetadata.status==='ready'?'Model ready':mlMetadata.status==='error'?'Model unavailable':'Model training'}</div></div>
   <div className="ml-importance">{importance.length?importance.slice(0,5).map((f,i)=><article key={f.feature}><em>0{i+1}</em><strong>{f.name}</strong><span>Importance: {f.importance.toFixed(3)}</span><p>{f.interpretation}</p></article>):<div className="ml-waiting">The time-based Random Forest model is training from the latest 365-day USGS catalog.</div>}</div>
   <div className="ml-scale"><span><i className="low"/>Low &lt; 0.35</span><span><i className="medium"/>Medium 0.35–0.65</span><span><i className="high"/>High &gt; 0.65</span><b>Likelihood score, not prediction certainty</b></div>
   <p className="ml-disclaimer">This model identifies historical-pattern-based hotspot likelihood. It does not predict exact earthquake timing, magnitude, or epicenter and must not be used for emergency response or public safety decisions. <strong>This is not an earthquake prediction or public warning system.</strong></p>
  </section>
  <section className="analytics panel"><div className="analytics-head"><div><small>EXPOSURE ANALYTICS</small><h2>Observed overlap, made legible</h2></div><div className="segment"><button className={tab==='population'?'active':''} onClick={()=>setTab('population')}>Population</button><button className={tab==='infrastructure'?'active':''} onClick={()=>setTab('infrastructure')}>Infrastructure</button></div></div>
   <div className="charts">{tab==='population'?<><article><h3>Top earthquakes by exposed population <small>{buffer} km buffer</small></h3><PopulationChart rows={pops} buffer={buffer}/></article><article><h3>Events by magnitude band <small>Filtered catalog</small></h3><MagnitudeChart events={eq}/></article><article className="cluster-table"><h3>Cluster register <small>DBSCAN historical patterns</small></h3><div className="table-head"><span>ID / STATUS</span><span>EVENTS</span><span>MAX</span><span>LATEST</span></div>{shownClusters.slice(0,5).map(c=><button key={c.id} onClick={()=>setSelected(c)}><span><i className={statusColor(c.status)}/><b>C-{String(c.id).padStart(2,'0')}</b><small>{c.status.replace(' hotspot','')}</small></span><span>{c.event_count}</span><span>M{c.max_magnitude}</span><span>{new Date(c.latest_event_time).toLocaleDateString([], {month:'short',day:'numeric'})}</span></button>)}</article></>:<><article><h3>Assets by category <small>{buffer} km buffer</small></h3><AssetsChart assets={shownAssets} buffer={buffer}/></article><article><h3>Assets by distance band <small>Cumulative exposure</small></h3><div className="distance-bars">{[50,100,200].map(v=><div key={v}><span><b>{v} km</b>{assets.filter(a=>ids.has(a.earthquake_id)&&a.distance_km<=v).length} assets</span><i><u style={{width:`${Math.min(100,assets.filter(a=>ids.has(a.earthquake_id)&&a.distance_km<=v).length/Math.max(1,shownAssets.length)*100)}%`}}/></i></div>)}</div></article><article><h3>Top events by critical assets <small>{buffer} km buffer</small></h3><div className="rank-list">{eq.map(e=>({e,n:shownAssets.filter(a=>a.earthquake_id===e.id).length})).sort((a,b)=>b.n-a.n).slice(0,5).map((x,i)=><button key={x.e.id} onClick={()=>setSelected(x.e)}><em>{i+1}</em><span>{x.e.place}<small>M{x.e.magnitude}</small></span><b>{x.n}</b></button>)}</div></article></>}</div>
  </section>
  <footer><div><strong>Open data, transparent methods.</strong><span>{summary.sources.map((s,i)=><span key={s.name}><a href={s.url} target="_blank">{s.attribution}</a> ({s.license}){i<summary.sources.length-1?'  •  ':''}</span>)}</span></div><div>Catalog updated {new Date(summary.updated_at).toLocaleString()}<br/>Population is approximate • OSM coverage may be incomplete • Exposure does not mean damage</div></footer>
  {loading&&<div className="loading"><PulseIcon/><span>Loading open seismic data</span></div>}{error&&<div className="error">API unavailable: {error}</div>}
 </main>
}






